// Agent Harness Module - Long-running task execution for agents
// Spec: .kiro/specs/agent-harnesses/tasks.md

export {
  // Core types
  type HarnessConfig,
  type HarnessState,
  type HarnessStatus,
  type HarnessPriority,
  type HarnessResult,
  type HarnessInfo,
  type HarnessMetrics,
  type HarnessError,
  type ExecutionPlan,
  type ExecutionStep,
  type StepStatus,
  type ToolCallRecord,
  type SubAgentResult,
  type SubAgentSpawnRequest,
  type HarnessCheckpoint,
  type CheckpointOptions,
  type HumanGateRequest,
  type HumanGateResponse,
  type AgentLoopSnapshot,
  type RecoveryStrategy,
  type DeadLetterEntry,
  type HarnessEvent,
  type HarnessEventType,
  type ResourceLimits,
  type ResourceUsage,
  type ToolPermission,
} from './types.js';

export {
  // Schemas
  HarnessStatusSchema,
  HarnessPrioritySchema,
  StepStatusSchema,
  HarnessEventTypeSchema,
  HarnessConfigSchema,
  HarnessStateSchema,
  HarnessResultSchema,
  HarnessInfoSchema,
  HarnessMetricsSchema,
  HarnessErrorSchema,
  ExecutionPlanSchema,
  ExecutionStepSchema,
  ToolCallRecordSchema,
  HarnessCheckpointSchema,
  CheckpointOptionsSchema,
  HumanGateRequestSchema,
  HumanGateResponseSchema,
  AgentLoopSnapshotSchema,
  RecoveryStrategySchema,
  DeadLetterEntrySchema,
  HarnessEventSchema,
  ResourceLimitsSchema,
  ResourceUsageSchema,
  // Validation functions
  validateHarnessConfig,
  validateHarnessState,
  parseHarnessState,
  validateExecutionPlan,
  validateCheckpoint,
  serializeHarnessState,
  deserializeHarnessState,
  // Type inference helpers
  type HarnessConfigInput,
  type HarnessStateInput,
  type HarnessResultInput,
  type ExecutionPlanInput,
  type ExecutionStepInput,
  type ToolCallRecordInput,
  type HarnessCheckpointInput,
  type HumanGateRequestInput,
  type HumanGateResponseInput,
  type RecoveryStrategyInput,
  type DeadLetterEntryInput,
} from './schemas.js';
